unset(LLVM_CONFIG CACHE)

find_program(
  LLVM_CONFIG REQUIRED NAMES llvm-config llvm-config-18 llvm-config-18.0
                             llvm-config180 llvm-config18 NAMES_PER_DIR)

if("${LLVM_CONFIG}" STREQUAL "LLVM_CONFIG-NOTFOUND")
  if(NOT LLVM_CONFIG_ERROR_MESSAGES STREQUAL "")
    list(JOIN LLVM_CONFIG_ERROR_MESSAGES "\n" LLVM_CONFIG_ERROR_MESSAGE)
    message(FATAL_ERROR ${LLVM_CONFIG_ERROR_MESSAGE})
  else()
    message(FATAL_ERROR "Unable to find llvm-config")
  endif()
endif()

execute_process(
  COMMAND ${LLVM_CONFIG} --version
  OUTPUT_VARIABLE LLVM_VERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND ${LLVM_CONFIG} --libdir
  OUTPUT_VARIABLE LLVM_LIBRARY_DIRS
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND ${LLVM_CONFIG} --includedir
  OUTPUT_VARIABLE LLVM_INCLUDE_DIR
  OUTPUT_STRIP_TRAILING_WHITESPACE)

option(LLVM_IS_SHARED "Use LLVM library with shared" ON)

if(LLVM_IS_SHARED)
  set(LLVM_LINK "--link-shared")
else()
  set(LLVM_LINK "--link-static")
endif(LLVM_IS_SHARED)

execute_process(
  COMMAND ${LLVM_CONFIG} --libs ${LLVM_LINK}
  OUTPUT_VARIABLE LLVM_LIBRARIES
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND ${LLVM_CONFIG} --cxxflags
  OUTPUT_VARIABLE LLVM_CXXFLAGS
  OUTPUT_STRIP_TRAILING_WHITESPACE)

execute_process(
  COMMAND ${LLVM_CONFIG} --cflags
  OUTPUT_VARIABLE LLVM_CFLAGS
  OUTPUT_STRIP_TRAILING_WHITESPACE)

if(LLVM_INCLUDE_DIR AND LLVM_LIBRARIES)
  set(LLVM_FOUND TRUE)
endif(LLVM_INCLUDE_DIR AND LLVM_LIBRARIES)
